### ISSUE TITLE
Renaming programs

### ISSUE THREAD

**Issue by viperML** [viperML/wrapper-manager#2]
e.g.: `nvim -> my-cool-nvim`

Maybe use a mapping of renames?

```nix
renames = {
  "nvim" = "my-cool-nvim";
}
```

**Comment by bew** [comment]
You might be interested in my `linkBins` builder (inspiration ?):
https://github.com/bew/dotfiles/blob/faf709cc766203e7b148b889e52b0d6914e6c918/nix/homes/mylib/mybuilders.nix#L4-L96

Which I use to link binaries, optionally renaming them as I want.
(I'm also thinking about a way to prefix all binaries from a pkg (by topic) to group them easily in autocompletion, but that's for later)
